// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoCWycYN-07whP152f4oKvL-xZmnsvLEg',
    appId: '1:808063464995:web:31c3e1412304a008d92396',
    messagingSenderId: '808063464995',
    projectId: 'dontaco-app',
    authDomain: 'dontaco-app.firebaseapp.com',
    storageBucket: 'dontaco-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDscw2iUEn_ZaPdDM5lxddUNIN2egsHxCo',
    appId: '1:808063464995:android:3537c692a032351fd92396',
    messagingSenderId: '808063464995',
    projectId: 'dontaco-app',
    storageBucket: 'dontaco-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLiT9t3f2ZNGXCjqMduXGZNYwwSJZ4UY',
    appId: '1:808063464995:ios:11151b41e92629ced92396',
    messagingSenderId: '808063464995',
    projectId: 'dontaco-app',
    storageBucket: 'dontaco-app.firebasestorage.app',
    iosBundleId: 'com.example.dontacoNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkLiT9t3f2ZNGXCjqMduXGZNYwwSJZ4UY',
    appId: '1:808063464995:ios:11151b41e92629ced92396',
    messagingSenderId: '808063464995',
    projectId: 'dontaco-app',
    storageBucket: 'dontaco-app.firebasestorage.app',
    iosBundleId: 'com.example.dontacoNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoCWycYN-07whP152f4oKvL-xZmnsvLEg',
    appId: '1:808063464995:web:bcbf64a993915bedd92396',
    messagingSenderId: '808063464995',
    projectId: 'dontaco-app',
    authDomain: 'dontaco-app.firebaseapp.com',
    storageBucket: 'dontaco-app.firebasestorage.app',
  );
}
